version: "3.9"

services:
  web:
    build: ./app
    container_name: stock_web
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - sqlite
    volumes:
      - db_data:/data  # SQLite DB file lives here

  redis:
    image: redis:7-alpine
    container_name: stock_redis
    ports:
      - "6379:6379"

  sqlite:
    build: ./sqlite
    container_name: stock_sqlite
    # A simple container that has the sqlite3 CLI available
    # Keep it running forever and forever and forever
    command: ["sh", "-c", "sleep infinity"]
    volumes:
      - db_data:/data

volumes:
  db_data:
